[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_dapp_with_react = "61WSjewfxM2gcD5dfgDXSCJB1La8zzam4tQi83yKjpFA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/vinhnguyen/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
